name = "gallery-mvp"
compatibility_date = "2026-03-02"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "GALLERY_DB"
database_name = "gallery"
database_id = "b5c8d5a9-a710-4ac7-8341-a619f852ef27"

[[r2_buckets]]
binding = "GALLERY_BUCKET"
bucket_name = "gallery"
preview_bucket_name = "gallery"
